name: CI - Build & GitOps Deploy

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: harbor.aisapi.com.tr/test/sample-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Install Harbor CA Certificate
        run: |
          echo "${{ secrets.HARBOR_CA_CERT }}" | sudo tee /usr/local/share/ca-certificates/harbor-ca.crt
          sudo update-ca-certificates
          sudo mkdir -p /etc/docker/certs.d/${{ secrets.HARBOR_URL }}
          echo "${{ secrets.HARBOR_CA_CERT }}" | sudo tee /etc/docker/certs.d/${{ secrets.HARBOR_URL }}/ca.crt
          
          # Bazı durumlarda docker daemon'ı restart etmek gerekebilir (Genelde runner'da gerekmez)
          # sudo systemctl restart docker

      - name: Docker login to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASS }}" | docker login \
            ${{ secrets.HARBOR_URL }} \
            -u ${{ secrets.HARBOR_USER }} \
            --password-stdin

      - name: Build & push image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Update GitOps repo (staging)
        env:
          GH_TOKEN: ${{ secrets.GITOPS_TOKEN }}
        run: |
          git clone https://$GH_TOKEN@github.com/${{ secrets.GITOPS_REPO }}.git
          cd sample-app-gitops
          sed -i "s/tag:.*/tag: $IMAGE_TAG/" environments/staging/values.yaml
          git config user.name "github-actions"
          git config user.email "ci@company.com"
          git commit -am "deploy(staging): sample-app $IMAGE_TAG"
          git push
